name: Desplegar Angular a la branca Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obtindre el codi
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instal·lar dependències
        run: |
          cd exemples-dwec/09-angular/2425/myrecipes
          npm install

      - name: Construir l'app Angular
        run: |
          cd exemples-dwec/09-angular/2425/myrecipes
          npm run build -- --output-path=dist

      - name: Pujar els fitxers construïts a Main
        run: |
          cd exemples-dwec/09-angular/2425/myrecipes
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          git commit -m "Desplegant la última versió"
          git push origin main
